{
 "title": "Service",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(http_requests_total{job=\"service\"}[1m])",
     "legendFormat": "requests"
    },
    {
     "expr": "irate(http_responses_total{job=\"service\"}[1m])",
     "legendFormat": "responses"
    }
   ]
  },
  {
   "title": "Decrypter Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(decrypter_pool_requests_total[1m])",
     "legendFormat": "pool"
    },
    {
     "expr": "irate(decrypter_worker_requests_total[1m])",
     "legendFormat": "worker"
    }
   ]
  },
  {
   "title": "Dep1 Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(extern_dep1_service_requests_total[1m])",
     "legendFormat": "requests"
    }
   ]
  }
 ]
}